### PR TITLE
move logo from drawer to header

### PR DESCRIPTION
**Pull request by RogerDodger**
If the logo is only 50x50px anyway, better to have it just one click away.

### CODE REVIEW

**Comment by alistair3149** [comment]
Not having the logo in the header is a design choice to be minimalistic, instead the branding element is present on the lower left corner in larger breakpoint. 

There is a specific height constraint to fit the logo into the header, ideally it has to be smaller than the header height and align with other icons (ideally 24px max as icons are 20px). Because of the height constraint, the icon and wordmark variant were considered to be the candidate to put on the header. However, there is a width constraint in smaller breakpoint as well, extensions like Echo and ULS will add more icon to the header tools and leave limited space. It is problematic because some wiki might have longer names and overcrowd the header. 

It might be revisited when the icon and wordmark syntax is more common and there is an alternative solution to the header crowding issue, but the current plan is to have the branding element inside the main menu.

image
image

**Comment by RogerDodger** [comment]
The header height is 56px, so at 50x50px it fits. At that size it's larger than the other icons, but that's not necessarily a problem.

If the logo is wide that's definitely an issue. But every logo is going to have a square form of some kind if only for the favicon. Is there no way to use the square logo specifically?

I checked for wrapping at 320px width (smallest width I'd personally design for), and it's still got 70px of space left with the 3 icons in the toolbar, so enough for at least one more. 

image

But 10px short with both ILS and Echo icons. In that case, you could display the logo up to the point where space runs out, and only then put it in the drawer, or you could reduce the space between the tool icons by just a little.

(The hamburger and logo probably should be ordered as in your screenshot, now that I go looking around at which way most other websites do it.)

A website without the logo in the header is pretty strange, since it's probably the single most common design websites use. The skin feels a little *too* nondescript without it. The wordmark in the lower left is just text, not adding any *visual* distinction to the site.

If this clashes with your design goals, then feel free to close the request. I submit patches upstream I think might be helpful, but with not much concern whether they be accepted or not.

**Comment by alistair3149** [comment]
There are two variants of the logo: icon and wordmark. They are added into MediaWiki core since 1.35 because of the new Vector/Desktop Improvement Project changes. Based on the documentation, we are taking the assumption that all icon would be a square and wordmark would be a rectangle, with a fallback to plain text wiki name. That is also why the skin no longer use `.mw-wiki-logo` because it is used by the older 1x and 2x logos in MW core. You can see [this page](https://www.mediawiki.org/wiki/Manual:$wgLogos) for more details.

> The header height is 56px, so at 50x50px it fits. At that size it's larger than the other icons, but that's not necessarily a problem.
The logo has to have sufficient padding in the header or else it will look too cramped, that is the reason I suggested 24px max height. 

> But 10px short with both ILS and Echo icons. In that case, you could display the logo up to the point where space runs out, and only then put it in the drawer, or you could reduce the space between the tool icons by just a little.
Further reducing the width of the tool buttons will reduce the click area of the button, making them more difficult to press with touchscreens (they are already reduced not long ago). As Echo is used on many wikis, I have to take the assumption that there will be at least five buttons in the header (theme, Echo alert, Echo notice, personal menu, search). One of the possible solution is to auto collapse the tool button and group them into another menu on the header, but it requires a lot of refactor and won't support noscript.

> A website without the logo in the header is pretty strange, since it's probably the single most common design websites use. The skin feels a little too nondescript without it. The wordmark in the lower left is just text, not adding any visual distinction to the site.
It is a common element in many websites but it is also not uncommon in complex web apps or apps to not have branding element in header. The tool buttons are more important than the header functionality-wise so they take the priority. As for the the wordmark in the lower left corner, it will be rewritten to support icon + wordmark logo if the wiki has them configured.

>If this clashes with your design goals, then feel free to close the request. I submit patches upstream I think might be helpful, but with not much concern whether they be accepted or not.
While this PR won't be merged because of the implementation, there is a possibility that it will be revisited soon and the discussion should be left open to see if there is more potential solutions.

**Comment by alistair3149** [comment]
Implemented in #288

**Pull request closed without merging**
