### PR TITLE
Add Math skinStyles

### PR DESCRIPTION
**Pull request by kuenzign**
I'm not sure of a good way to accomplish this using CSS variables instead of LESS variables, that is why this is marked as Grade E.  If anyone has suggestions on how to do this properly with CSS variables, let me know.

### CODE REVIEW

**Comment by alistair3149** [comment]
Do you happen to have a screenshot or a live site of how it would work?
I wasn't able to set up the extension locally so I am just how it would work

**Comment by kuenzign** [comment]
I don't have a publicly available site that you can look at, but here are some screenshots of what it looks like with and without the changes:

# Without Changes:
dark mode without changes
light mode without changes

# With Changes:
dark mode with changes
light mode with changes

Yes, an invert (and perhaps a hue rotate) would work, but in my opinion it looks way better when the color matches the text color exactly, especially with the math syntax inline with the text.

**Comment by kuenzign** [comment]
These changes match the color (including the alpha/opacity) of the text exactly by using the SVG filter.  Doing a full invert looks a bit jarring in my opinion.

**Comment by alistair3149** [comment]
Yeah sadly there isn't a CSS only and variable way to achieve the same function currently. Merging this now. Thanks for the PR!

**Pull request merged**
