### PR TITLE
Display registration date, contribution link and gender on usepages; allow citizen-tagline* to be fully parsed

### PR DESCRIPTION
**Pull request by Dringsim**
image

### CODE REVIEW

**Comment by alistair3149** [comment]
That looks awesome, thanks a ton for making a patch for it :D

For the gender sign, I think it might get complicated when it comes to non-binary genders. It might be more suitable to go for preferred pronouns instead, as it is also how the MediaWiki core preference was referring to:

image

Since there are no such messages in core, we might have to create it ourselves. The end of the message key (e.g. `male) refers to the parameter from MW core. The message key is generic as it might be used in other parts of Citizen.
```json
{
    "citizen-pronouns-subjective-male": "He",
    "citizen-pronouns-objective-male": "Him",
    "citizen-pronouns-possessive-male": "His",
    "citizen-pronouns-subjective-female": "She",
    "citizen-pronouns-objective-female": "Her",
    "citizen-pronouns-possessive-female": "Hers",
    "citizen-pronouns-subjective-notknown": "They",
    "citizen-pronouns-objective-notknown": "Them",
    "citizen-pronouns-possessive-notknown": "Theirs"
}
```

Lastly, would you mind to reorder the items so it goes by gender > edits > registration date? Here's a mockup:
image

**Comment by Dringsim** [comment]
Hmm... many languages don't have pronoun declension. Use {{GENDER:|He|She|They}}?

**Comment by Dringsim** [comment]
I perfer gender signs than pronouns in tagline. Though pronouns in bios are familiar to English-speaking users, they may make other users confused - I have ever seen many trans persons put English pronouns in their bios while surrounding text is in Chinese.

**Comment by alistair3149** [comment]
> I perfer gender signs than pronouns in tagline. Though pronouns in bios are familiar to English-speaking users, they may make other users confused - pronouns are rarely used in bios in Chinese-speaking community; I have ever seen many trans persons put English pronouns in their bios while surrounding text is in Chinese (Mandarin). Also, in many languages, pronouns are gender-neutral. {{GENDER:|He|She|They}} in Turkish may be {{GENDER:|o|o|o}}. Users can't guess what it is.

Yes you are right. I didn't consider gender-neutral languages like Turkish where it would be confusing as it is using the same pronouns. I have reverted to the gender symbol implementation in [c793959](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/c793959416ce28fff0ddebebff6252f005b6aa52).

Again thank you so much for the PR and the additional insights!

**Pull request merged**
