### PR TITLE
feat: "A" status for PortableInfobox

### PR DESCRIPTION
**Pull request by lens0021**
image

A part of #442.

The design was originally on https://starcitizen.tools/Special:Redirect/revision/184546 and written by @alistair3149, but modified to fit with PortableInfobox.

Thank you.

### CODE REVIEW

**Comment by alistair3149** [comment]
I would need some time to check on this one since PortableInfobox is used on a lot of wikis. Will get back to you later.

**Comment by alistair3149** [comment]
Hmm is there a way to query which wikis use both PI and Citizen together?

I am a bit hesitate on this one since my assumption is that infoboxes are usually heavily customized by wikis. By applying additional styles that are not a part of the original design, that can be disruptive to wikis and they would need additional styles to override it.

However, I have never used PI nor I am familiar with common usage for it. I think that I would need more input on this matter from more wiki admins that use both to determine what is the best approach.

**Comment by lens0021** [comment]
I understand and agree with that.

And about the query: I am not an expert on Semantic MediaWiki so cannot optimize the query on WikiApiary to use AND search. However according to WikiApiary,

- [Citizen skin is installed on 68 wikis and all wikis are on neither Fandom, Wikia, or Gamepedia.](https://wikiapiary.com/w/index.php?title=Special%3AAsk&q=%5B%5BHas+subobject.Has+skin%3A%3ASkin%3ACitizen%5D%5D&po=%3FHas+sitename%3DWiki%0D%0A%3FHas+URL%3DURL%0D%0A%3FHas+farm%3DFarm%0D%0A%3FHas+active+users+count%3DUsers%0D%0A%3FHas+pages+count%3Dpages%0D%0A%3FHas+article+count%3Darticle%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=100&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=-&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&eq=yes)
- [PortableInfobox is installed on 78 wikis if the farms mentioned above are excluded.](https://wikiapiary.com/w/index.php?title=Special%3AAsk&q=%5B%5BHas+subobject.Has+extension%3A%3AExtension%3APortable+Infobox%5D%5D%0D%0A%5B%5BHas+farm%3A%3A%21Wikia%5D%5D%0D%0A%5B%5BHas+farm%3A%3A%21Gamepedia%5D%5D%0D%0A%5B%5BHas+farm%3A%3A%21Fandom%5D%5D%0D%0A%5B%5BHas+farm%3A%3A%21Wikia.org%5D%5D&po=%3FHas+sitename%3DWiki%0D%0A%3FHas+URL%3DURL%0D%0A%3FHas+farm%3DFarm%0D%0A%3FHas+active+users+count%3DUsers%0D%0A%3FHas+pages+count%3Dpages%0D%0A%3FHas+article+count%3Darticle%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=100&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=-&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&eq=yes)
- The wikis on the intersection are:
  - Batman Family Wiki **(Closed)** 	https://batfamily.miraheze.org/wiki/
  - CLG Wiki	https://closinglogosgroup.miraheze.org
  - Chouverse Wiki	https://chouverse.cludisciples.cyou/
  - Circleyverse Wiki **(Closed)** 	https://circleyverse.miraheze.org
  - Ficreation **(404 Wiki Not Found)**	https://ficreation.miraheze.org/wiki/Main_Page
  - Wiki Lớp Học Mật Ngữ	https://lhmn.miraheze.org/
  - WikiBen	https://wikiben.miraheze.org
  - WikiHood	https://wikihood.miraheze.org/wiki/
  - Wordle Hub **(This is my wiki)**	https://wordles.miraheze.org/
  - Wjghj Project Statics	https://common.wjghj.cn/

But please note that the above list is not complete because of https://phabricator.wikimedia.org/T292651.

**Comment by alistair3149** [comment]
Closing for now.

I'm both sorry and thankful for the work that you have done with PI.

The primary concern is that PI is often heavily customized on wikis, introducing extra styles that are not a part of the original spec will break custom styles on wikis and require additional CSS overrides.

**Pull request closed without merging**
