### PR TITLE
Added translation for citizen-tagline-user-regdate in Spanish.

### PR DESCRIPTION
**Pull request by danielyepezgarces**
This key was not translated and used the English language by default.

### CODE REVIEW

**Comment by alistair3149** [comment]
Hi there! Thank you for the PR. All of our translations are handled through [TranslateWiki](https://translatewiki.net/w/i.php?title=Special%3ATranslate&group=mwgithub-star-citizen&language=es&filter=%21translated&optional=undefined&action=translate), would you mind to translate there instead?

**Comment by danielyepezgarces** [comment]
> Hi there! Thank you for the PR. All of our translations are handled through [TranslateWiki](https://translatewiki.net/w/i.php?title=Special%3ATranslate&group=mwgithub-star-citizen&language=es&filter=%21translated&optional=undefined&action=translate), would you mind to translate there instead?

I don't know how to use this platform, and that message doesn't appear, so I prefer to use the conventional method.

**Comment by alistair3149** [comment]
> > Hi there! Thank you for the PR. All of our translations are handled through [TranslateWiki](https://translatewiki.net/w/i.php?title=Special%3ATranslate&group=mwgithub-star-citizen&language=es&filter=%21translated&optional=undefined&action=translate), would you mind to translate there instead?
> 
> I don't know how to use this platform, and that message doesn't appear, so I prefer to use the conventional method.

The message is on there but I added the translation for you there. It should be merged into the main branch within a few days.

**Comment by danielyepezgarces** [comment]
ok, well in another occasion I will write again since I have a specific list of design flaws that I have seen

I use the master version of MediaWiki, so I'm keeping an eye on the latest stuff that's being loaded and its bundled extensions.

**Pull request closed without merging**
