### PR TITLE
feat: ✨ add UserProfileV2 style

### PR DESCRIPTION
**Pull request by songnguxyz**
Converted to variables.

## Summary by CodeRabbit

- **New Features**
	- Introduced new styling options for the user profile section, enhancing visual appeal and user experience.
	- Added a dedicated stylesheet for UserProfileV2, improving the design consistency and interactivity of user profile elements.

### CODE REVIEW

**Comment by songnguxyz** [comment]
@coderabbitai review

**Comment by alistair3149** [comment]
LGTM. Would you be able to add it to README.md as well?

**Comment by songnguxyz** [comment]
> LGTM. Would you be able to add it to README.md as well?

No problem, thanks for the signal!
> After I fix the badge text...

**Comment by songnguxyz** [comment]
@alistair3149 GTG, ready to merge!

**Pull request merged**
